"""added more enums

Revision ID: f9ed3ad82db1
Revises: 073155860461
Create Date: 2026-03-04 21:59:01.528196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ed3ad82db1'
down_revision: Union[str, Sequence[str], None] = '073155860461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # pass
    # ### end Alembic commands ###
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'PDF_COMPRESS';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'PDF_COMPRESS_PRO';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'IMAGE_TO_PDF';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'PDF_TO_IMAGE';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'EXIF_SCRUBBER';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'HEIC_TO_IMAGE';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'IMAGE_TO_HEIC';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'IMAGE_COLOR_EFFECTS';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'IMAGE_DPI_CHANGER';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'IMAGE_DPI_CHECKER';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'PASSWORD_GENERATOR';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'EXTRACT_PDF_IMAGES';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'VIDEO_TO_STICKER';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'IMAGE_TO_STICKER';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'VIDEO_TO_GIF';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'IMAGE_TO_GIF';")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'WATERMARK_IMAGES';")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
